# Generated by Django 3.1.2 on 2020-10-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verfied',
            new_name='is_verified',
        ),
    ]
