# Generated by Django 3.1.2 on 2020-10-12 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201011_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
