# Generated by Django 3.0 on 2020-10-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('product', '0008_usercustom_plugin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hello',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='usercustom_plugin',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
        migrations.DeleteModel(
            name='Menu_Item',
        ),
        migrations.DeleteModel(
            name='UserCustom_Plugin',
        ),
    ]
