# Generated by Django 3.0 on 2020-10-26 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('product', '0010_employee_hello_menu_item_usercustom_plugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Custom_Plugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='product_user_custom_plugin', serialize=False, to='cms.CMSPlugin')),
                ('items_per_page', models.PositiveIntegerField(default=0, help_text='Show number of items per page', verbose_name='Items per page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.DeleteModel(
            name='UserCustom_Plugin',
        ),
    ]
